#------------------------------------
# imported modules
#------------------------------------
import random
import smtplib
import tkinter as tk
from tkinter import messagebox
from tkinter import ttk

# Define the sender email and password
sender_email = "Enter Your email"
sender_password = "Password generated by Apppasword on GMAIL"

# Create a function to send OTP via email
def send_otp(recipient_email):
    # Generate a random 6-digit OTP
    otp = ''.join([str(random.randint(0, 9)) for i in range(6)])

    # Create the email message
    message = f"Subject: Your OTP\n\nYour OTP is: {otp}"

    # Send the OTP via email
    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.starttls()
    server.login(sender_email, sender_password)
    server.sendmail(sender_email, recipient_email, message)
    server.quit()

    # Return the OTP value
    return otp

# Create a function to verify the OTP
def verify_otp():
    # Get the entered email and OTP from the user input
    entered_email = email_entry.get()
    entered_otp = otp_entry.get()

    # Send a verification message based on the entered email and OTP
    if entered_email == "" or entered_otp == "":
        messagebox.showerror("Error", "Please enter both email and OTP")
    elif entered_otp == otp:
        messagebox.showinfo("Verification", "Verification successful!")
    else:
        messagebox.showerror("Verification", "Verification failed.")

# Create a function to send another OTP to the same email
def send_again():
    global otp_sent, otp
    otp_sent = False
    otp_label.config(text="")
    otp_entry.delete(0, tk.END)

#------------------------------------
# Create a GUI window
#------------------------------------
window = tk.Tk()
window.title("OTP Verification")

# Set the window size and center it on the screen
window_width = 550
window_height = 400
screen_width = window.winfo_screenwidth()
screen_height = window.winfo_screenheight()
x = int(screen_width / 2 - window_width / 2)
y = int(screen_height / 2 - window_height / 2)
window.geometry(f"{window_width}x{window_height}+{x}+{y}")

# Set the window background color to light blue
window.config(bg="light blue")

# Create an input field for the email address
email_entry = ttk.Entry(window, width=30, font=("Arial", 11), justify="center")
email_entry.pack(pady=20)


# Create a button to send the OTP and a label to display the sent OTP
otp_sent = False
def send_otp_button():
    global otp_sent, otp
    if otp_sent:
        messagebox.showinfo("OTP Sent", "OTP has already been sent to this email")
    else:
        recipient_email = email_entry.get()
        if recipient_email == "":
            messagebox.showerror("Error", "Please enter an email address")
        else:
            otp_sent = True
            otp = send_otp(recipient_email)
            otp_label.config(text=f"OTP sent to {recipient_email}")
otp_button = ttk.Button(window, text="Send OTP", command=send_otp_button)
otp_button.pack()

otp_label = ttk.Label(window, text="")
otp_label.pack(pady=20)

# Create a button to send another OTP
send_again_button = ttk.Button(window, text="Send Again", command=send_again)
send_again_button.pack(pady=10)

# Create an input field for the OTP and a button to verify it
otp_entry = ttk.Entry(window, width=15, font=("Arial", 11), justify="center")
otp_entry.pack()
verify_button = ttk.Button(window, text="Verify", command=verify_otp)
verify_button.pack(pady=20)

#------------------------------------
# Start the GUI main loop
#------------------------------------
window.mainloop()